[mgr]
show_hidden = true

[opener]
#
# Edit
nvim = [
	{ run = "$HOME/.local/bin/nvim %s", block = true, for = "unix", desc = "Neovim" },
]
code = [
  { run = 'code "$@"', orphan = true, desc = "VS Code", for = "unix" },
]
#
# PDF
zathura = [
	{ run = 'zathura "$@"', orphan = true, for = "unix", desc = "Zathura" },
]
okular = [
	{ run = 'okular "$@"', orphan = true, for = "unix", desc = "Okular" },
]
#
# Browser
brave = [
	{ run = 'brave-browser "$@"', orphan = true, for = "unix", desc = "Brave" },
]
firefox = [
	{ run = 'firefox "$@"', orphan = true, for = "unix", desc = "Firefox" },
]
#
# Media
image_viewer = [
	{ run = 'loupe "$@"', desc = "Image Viewer", orphan = true, for = "unix" }
]
video_viewer = [
	{ run = 'totem "$@"', desc = "Video Viewer", orphan = true, for = "unix" }
]
kdenlive = [
	{ run = 'kdenlive "$@"', desc = "Kdenlive", orphan = true, for = "unix" }
]
#
# Reveal
reveal = [
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]

[open]
rules = [
  # Code
	{ mime = "text/html",  use = [ "brave", "nvim", "code", "firefox", "reveal" ] },
	{ mime = "text/*",  use = [ "nvim", "code", "reveal" ] },
	{ mime = "application/json", use = [ "nvim", "code", "reveal" ] },

  # Media
  { mime = "application/pdf", use = [ "zathura", "okular", "brave", "firefox", "reveal" ] },
	{ mime = "image/*", use = "image_viewer", "reveal" },
	{ mime = "video/*", use = ["video_viewer", "kdenlive", "reveal"] },

  # Base
	{ name = "*/", use = [ "nvim", "code", "reveal" ] },
	{ mime = "*", use = [ "nvim", "code", "reveal" ] }
]
