custom_configurations:
  int:
    Sharp Corporation 0x1515 0x00000000:
      active: false
    BenQ Corporation BenQ EL2870U A3K00708SL0:
      active: true
      resolution:
        - 3490
        - 1963
      scale: 1.100000023841858
      refresh_rate: 59997
      workspaces:
        - "1"
        - music
default_configurations:
  ? - BenQ Corporation BenQ EL2870U A3K00708SL0
    - Sharp Corporation 0x1515 0x00000000
  : Sharp Corporation 0x1515 0x00000000:
      active: false
    BenQ Corporation BenQ EL2870U A3K00708SL0:
      active: true
      resolution:
        - 3310
        - 1862
      scale: 1.1599999666213987
      refresh_rate: 59997
      workspaces:
        - "1"
        - "2"
        - music
  ? - Sharp Corporation 0x1515 0x00000000
  : Sharp Corporation 0x1515 0x00000000:
      active: true
      resolution:
        - 1920
        - 1200
      refresh_rate: 59950
      workspaces:
        - "1"
        - "2"
  ? - Dell Inc. DELL S2721DS B2G3R43
    - Sharp Corporation 0x1515 0x00000000
  : Dell Inc. DELL S2721DS B2G3R43:
      active: true
      resolution:
        - 2560
        - 1440
      position:
        - 1920
        - 0
      refresh_rate: 59951
      workspaces: [1, 2, 3, 4, 5]
    Sharp Corporation 0x1515 0x00000000:
      active: true
      resolution:
        - 1920
        - 1200
      position:
        - 2220
        - 1440
      refresh_rate: 59950
      workspaces:
        - music
  ? - Dell Inc. DELL S3422DWG 48LXSH3
    - Sharp Corporation 0x1515 0x00000000
  : Dell Inc. DELL S3422DWG 48LXSH3:
      active: true
      resolution:
        - 3440
        - 1440
      refresh_rate: 59973
      workspaces:
        - "1"
        - "2"
        - music
    Sharp Corporation 0x1515 0x00000000:
      active: false
  ? - Dell Inc. DELL S3422DWG 48LXSH3
    - "Goldstar Company Ltd LG FULL HD "
    - Sharp Corporation 0x1515 0x00000000
  : Sharp Corporation 0x1515 0x00000000:
      active: false
    Dell Inc. DELL S3422DWG 48LXSH3:
      active: true
      resolution:
        - 3440
        - 1440
      position:
        - 0
        - 480
      refresh_rate: 143975
      workspaces:
        - "1"
    "Goldstar Company Ltd LG FULL HD ":
      active: true
      resolution:
        - 1080
        - 1920
      position:
        - 3440
        - 230
      rotation: "90"
      refresh_rate: 60000
      workspaces:
        - music
