# Fonts & Styling
default_font: &default_font Hack Nerd Font Mono:pixelsize=12
icon_font: &icon_font Hack Nerd Font 6 Free:style=solid:pixelsize=14
icon_font_brands: &icon_font_brands Hack Nerd Font Mono 6 Brands:pixelsize=16
std_underline: &std_underline { underline: { size: 2, color: ff0000ff } }

# Theme
fg_color: &fg_color e8e8e8ff
bg_color: &bg_color 242424ff

# Colours
white_deco: &white_deco { background: { color: ffffffff } }
fade_white_deco: &fade_white_deco { background: { color: ffffff33 } }
white: &white ffffffff

# States
good_deco: &good_deco { background: { color: 00b061ff } }
warn_deco: &warn_deco { background: { color: e66f00ff } }
error_deco: &error_deco { background: { color: ff003cff } }

# Margin
deco_margin: &deco_margin 10
icon_margin: &icon_margin 10

bar:
  height: 20
  location: top
  spacing: 10
  margin: 7

  # Default font
  font: Hack Nerd Font Mono:pixelsize=12

  foreground: *fg_color
  background: *bg_color

  left:
    - i3:
        sort: ascending
        anchors: # Not used (directly) by f00bar; used here to avoid duplication
          - string:
              &i3_common {
                margin: 7,
                on-click: "swaymsg --quiet workspace {name}",
              }
          - string: &default { <<: *i3_common, text: "{name}" }
          - string: &main { <<: *i3_common, text: , font: *icon_font }
          - string:
              &surfing { <<: *i3_common, text: , font: *icon_font_brands }
          - string: &misc { <<: *i3_common, text: , font: *icon_font }
          - string: &mail { <<: *i3_common, text: , font: *icon_font }
          - string: &music { <<: *i3_common, text: 󰼛, font: *icon_font }
          - focused: &focused
              foreground: *bg_color
              deco: { stack: [*white_deco] }
          - invisible: &invisible
              foreground: *fg_color
              deco: *fade_white_deco
          - urgent: &urgent
              foreground: *fg_color
              deco: { stack: [*error_deco] }
          - map: &i3_mode
              default:
                - string:
                    margin: 5
                    text: "{mode}"
                    deco: { background: { color: cc421dff } }
                - empty: { right-margin: 7 }
              conditions:
                mode == default: { empty: {} }
        content:
          "":
            map:
              conditions:
                state == focused: { string: { <<: [*default, *focused] } }
                state == unfocused: { string: { <<: *default } }
                state == invisible: { string: { <<: [*default, *invisible] } }
                state == urgent: { string: { <<: [*default, *urgent] } }
          main:
            map:
              conditions:
                state == focused: { string: { <<: [*main, *focused] } }
                state == unfocused: { string: { <<: *main } }
                state == invisible: { string: { <<: [*main, *invisible] } }
                state == urgent: { string: { <<: [*main, *urgent] } }
          surfing:
            map:
              conditions:
                state == focused: { string: { <<: [*surfing, *focused] } }
                state == unfocused: { string: { <<: *surfing } }
                state == invisible: { string: { <<: [*surfing, *invisible] } }
                state == urgent: { string: { <<: [*surfing, *urgent] } }
          misc:
            map:
              conditions:
                state == focused: { string: { <<: [*misc, *focused] } }
                state == unfocused: { string: { <<: *misc } }
                state == invisible: { string: { <<: [*misc, *invisible] } }
                state == urgent: { string: { <<: [*misc, *urgent] } }

          mail:
            map:
              conditions:
                state == focused: { string: { <<: [*mail, *focused] } }
                state == unfocused: { string: { <<: *mail } }
                state == invisible: { string: { <<: [*mail, *invisible] } }
                state == urgent: { string: { <<: [*mail, *urgent] } }
          music:
            map:
              conditions:
                state == focused: { string: { <<: [*music, *focused] } }
                state == unfocused: { string: { <<: *music } }
                state == invisible: { string: { <<: [*music, *invisible] } }
                state == urgent: { string: { <<: [*music, *urgent] } }
    # - label:
    #     content:
    #       - string:
    #           on-click: /bin/sh -c "/home/$USER/.config/scripts/theme-toggle.sh dark"
    #           text: "○ "
    #           font: *iconefont
    #       - string:
    #           on-click: /bin/sh -c "/home/$USER/.config/scripts/theme-toggle.sh light"
    #           text: " ●"
    #           font: *icon_font
    - label:
        content:
          - string:
              {
                text: "DEV [",
                on-click: /bin/sh -c "/home/$USER/.config/wofi/bt_device_toggle/launch.sh",
              }
          - string:
              {
                text: "⬓ ",
                font: *icon_font,
                on-click: /bin/sh -c "sway output eDP-1 toggle; killall yambar; yambar &",
              }
          - string:
              {
                text: "▭  ▯",
                font: *icon_font,
                on-click: /bin/sh -c "wdisplays",
              }
          - string: { text: "]" }
    - foreign-toplevel:
        content:
          - map:
              conditions:
                ~activated: { empty: {} }
                activated:
                  - string:
                      {
                        text: "{app-id}",
                        foreground: *white,
                        deco: *fade_white_deco,
                        margin: *deco_margin,
                      }
                  # - string: { text: " {title}", max: 25, right-margin: 10 }

  center:
    - clock:
        time-format: "%H:%M %p"
        date-format: "%^a %d.%m.%Y"
        content:
          - string:
              {
                text: "{time} - {date}",
                foreground: *white,
                deco: *fade_white_deco,
                margin: 25,
              }

  right:
    - backlight:
        name: intel_backlight
        content:
          - string: { text: " LUM {percent}% " }
    - pulse:
        content:
          map:
            conditions:
              ~online: { string: { text: "MIC ERR" } }
              online:
                map:
                  conditions:
                    source_muted:
                      - string:
                          {
                            text: "MIC MUT",
                            margin: *deco_margin,
                            deco: *error_deco,
                            on-click: /bin/sh -c "amixer set Capture toggle",
                          }
                      - string:
                          {
                            text: " [{source_port}",
                            max: 11,
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/pulse-source-toggle.sh",
                          }
                      - string: { text: "]" }
                    ~source_muted:
                      - string:
                          {
                            text: "MIC {source_percent}%",
                            on-click: /bin/sh -c "amixer set Capture toggle",
                          }
                      - string:
                          {
                            text: " [{source_port}",
                            max: 11,
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/pulse-source-toggle.sh",
                          }
                      - string: { text: "]" }
    - pulse:
        content:
          map:
            conditions:
              ~online: { string: { text: "SPK ERR" } }
              online:
                map:
                  conditions:
                    sink_muted:
                      - string:
                          {
                            text: "VOL MUT",
                            margin: *deco_margin,
                            deco: *warn_deco,
                            on-click: /bin/sh -c "amixer set Master toggle",
                          }
                      - string:
                          {
                            text: " [{sink_port}",
                            max: 10,
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/pulse-sink-toggle.sh",
                          }
                      - string: { text: "]" }
                    ~sink_muted:
                      - string:
                          {
                            text: "VOL {sink_percent}%",
                            on-click: /bin/sh -c "amixer set Master toggle",
                          }
                      - string:
                          {
                            text: " [{sink_port}",
                            max: 10,
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/pulse-sink-toggle.sh",
                          }
                      - string: { text: "]" }
    - network:
        name: wlp0s20f3
        poll-interval: 60
        content:
          map:
            default:
              - string:
                  {
                    text: "NET OK",
                    margin: *deco_margin,
                    deco: *warn_deco,
                    on-click: /bin/sh -c "foot nmtui",
                  }
            conditions:
              state == down:
                - string:
                    {
                      text: "OFFLINE",
                      margin: *deco_margin,
                      deco: *error_deco,
                      on-click: /bin/sh -c "foot nmtui",
                    }
              state == up:
                - string: { text: "NET {signal} [" }
                - string: { text: "{ssid}", max: 15 }
                - string: { text: "]" }
    - battery:
        name: BAT0
        poll-interval: 60
        content:
          map:
            conditions:
              state == unknown:
                - string:
                    {
                      text: "BAT {capacity}% [{estimate}]",
                      on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/powerprofile-toggle.sh",
                    }
              state == discharging:
                map:
                  conditions:
                    capacity > 25:
                      - string:
                          {
                            text: "BAT {capacity}% [{estimate}]",
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/powerprofile-toggle.sh",
                          }
                    capacity <= 25:
                      - string:
                          {
                            text: "BAT {capacity}% [{estimate}]",
                            margin: *deco_margin,
                            deco: *warn_deco,
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/powerprofile-toggle.sh",
                          }
                    capacity <= 15:
                      - string:
                          {
                            text: "BAT LOW {capacity}% [{estimate}]",
                            margin: *deco_margin,
                            deco: *error_deco,
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/powerprofile-toggle.sh",
                          }
              state == "not charging":
                - string:
                    {
                      text: "EXT {capacity}% [{estimate}]",
                      margin: *deco_margin,
                      deco: *warn_deco,
                      on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/powerprofile-toggle.sh",
                    }
              state == charging:
                map:
                  conditions:
                    capacity > 80:
                      - string:
                          {
                            text: "CHG HIGH {capacity}% [{estimate}]",
                            margin: *deco_margin,
                            deco: *error_deco,
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/powerprofile-toggle.sh",
                          }
                    capacity <= 80:
                      - string:
                          {
                            text: "CHG {capacity}% [{estimate}]",
                            margin: *deco_margin,
                            deco: *good_deco,
                            on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/powerprofile-toggle.sh",
                          }
              state == full:
                - string:
                    {
                      text: "EXT {capacity}% [CHG FULL]",
                      margin: *deco_margin,
                      deco: *error_deco,
                      on-click: /bin/sh -c "/home/$USER/.config/yambar/scripts/powerprofile-toggle.sh",
                    }
    - label:
        content:
          - string:
              on-click: /bin/sh -c "swaymsg reload"
              text: 󰜉
              font: *icon_font
          - string:
              on-click: /bin/sh -c "/home/$USER/.config/wofi/powermenu/launch.sh"
              margin: *icon_margin
              text: 
              font: *icon_font
